version: 2.1

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0-RC1

commands:
  run_jvm_tests:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! buildJVM bench/test

  run_js_tests:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! validateJS && sbt ++<< parameters.scala_version >>! validateKernelJS && sbt ++<< parameters.scala_version >>! validateFreeJS

  check_bincompat:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! validateBC

jobs:
  linting:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: sbt scalastyle fmtCheck

  scalafix:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: cd scalafix && sbt tests/test

  bincompat_check:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - check_bincompat:
          scala_version: *scala_version_211
      - check_bincompat:
          scala_version: *scala_version_212

  coverage:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: sbt coverage buildJVM bench/test coverageReport

  test_jvm_211:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_jvm_tests:
          scala_version: *scala_version_211

  test_js_211:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_js_tests:
          scala_version: *scala_version_211

  test_jvm_212:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_jvm_tests:
          scala_version: *scala_version_212

  test_js_212:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_js_tests:
          scala_version: *scala_version_212

  test_jvm_213:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_jvm_tests:
          scala_version: *scala_version_213

  test_js_213:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - run_js_tests:
          scala_version: *scala_version_213

workflows:
  version: 2
  build:
    jobs:
      - linting
      - scalafix
      - bincompat_check
      - coverage:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_jvm_211:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_js_211:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_jvm_212:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_js_212:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_jvm_213:
          requires:
            - linting
            - scalafix
            - bincompat_check
      - test_js_213:
          requires:
            - linting
            - scalafix
            - bincompat_check

