version: 2.1

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0-RC1

commands:
  run_jvm_tests:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! buildJVM bench/test

  run_js_tests:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! validateJS && sbt ++<< parameters.scala_version >>! validateKernelJS && sbt ++<< parameters.scala_version >>! validateFreeJS

  check_bincompat:
    parameters:
      scala_version:
        type: string
    steps:
      - checkout
      - run: sbt ++<< parameters.scala_version >>! validateBC

jobs:
  linting:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: sbt scalastyle fmtCheck

  scalafix:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: cd scalafix && sbt tests/test

  bincompat_check:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    parallelism: 3
    steps:
      - check_bincompat:
          scala_version: *scala_version_211
      - check_bincompat:
          scala_version: *scala_version_212
      - check_bincompat:
          scala_version: *scala_version_213

  coverage:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    steps:
      - checkout
      - run: sbt coverage buildJVM bench/test coverageReport

  test_all:
    docker:
      - image: dgregory084/cats-builder:0.1.0
    parallelism: 6
    steps:
      - run_jvm_tests:
          scala_version: *scala_version_211
      - run_jvm_tests:
          scala_version: *scala_version_212
      - run_jvm_tests:
          scala_version: *scala_version_213
      - run_js_tests:
          scala_version: *scala_version_211
      - run_js_tests:
          scala_version: *scala_version_212
      - run_js_tests:
          scala_version: *scala_version_213

workflows:
  version: 2
  build:
    jobs:
      - linting
      - scalafix
      - bincompat_check
      - coverage:
          requires: 
            - linting
            - scalafix
            - bincompat_check
      - test_all:
          requires: 
            - linting
            - scalafix
            - bincompat_check
